Resources:
  ProductsTable241ADBFF:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      TableName: products
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
    Metadata:
      aws:cdk:path: BecsCdkStack/ProductsTable/Resource
  BecsApiGateway1D5DB2B6:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Description: API Gateway with BECS Lambdas.
      Name: BECS API Gateway
    Metadata:
      aws:cdk:path: BecsCdkStack/BecsApiGateway/Resource
  BecsApiGatewayCloudWatchRoleE8C26C9B:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: apigateway.amazonaws.com
        Version: "2012-10-17"
      ManagedPolicyArns:
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/service-role/AmazonAPIGatewayPushToCloudWatchLogs
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
    Metadata:
      aws:cdk:path: BecsCdkStack/BecsApiGateway/CloudWatchRole/Resource
  BecsApiGatewayAccountEDEB47D1:
    Type: AWS::ApiGateway::Account
    Properties:
      CloudWatchRoleArn:
        Fn::GetAtt:
          - BecsApiGatewayCloudWatchRoleE8C26C9B
          - Arn
    DependsOn:
      - BecsApiGateway1D5DB2B6
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
    Metadata:
      aws:cdk:path: BecsCdkStack/BecsApiGateway/Account
  BecsApiGatewayDeployment568E931A7f3ac93ea3ae8dda97325968eb337d4e:
    Type: AWS::ApiGateway::Deployment
    Properties:
      Description: API Gateway with BECS Lambdas.
      RestApiId:
        Ref: BecsApiGateway1D5DB2B6
    DependsOn:
      - BecsApiGatewayreportsGET493B545F
      - BecsApiGatewayreportsPOST96506AE4
      - BecsApiGatewayreportsF831456D
    Metadata:
      aws:cdk:path: BecsCdkStack/BecsApiGateway/Deployment/Resource
  BecsApiGatewayDeploymentStageprod3FC6D306:
    Type: AWS::ApiGateway::Stage
    Properties:
      DeploymentId:
        Ref: BecsApiGatewayDeployment568E931A7f3ac93ea3ae8dda97325968eb337d4e
      RestApiId:
        Ref: BecsApiGateway1D5DB2B6
      StageName: prod
    DependsOn:
      - BecsApiGatewayAccountEDEB47D1
    Metadata:
      aws:cdk:path: BecsCdkStack/BecsApiGateway/DeploymentStage.prod/Resource
  BecsApiGatewayreportsF831456D:
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId:
        Fn::GetAtt:
          - BecsApiGateway1D5DB2B6
          - RootResourceId
      PathPart: reports
      RestApiId:
        Ref: BecsApiGateway1D5DB2B6
    Metadata:
      aws:cdk:path: BecsCdkStack/BecsApiGateway/Default/reports/Resource
  BecsApiGatewayreportsGETApiPermissionBecsCdkStackBecsApiGateway9CE4D45CGETreportsF1CBE695:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Fn::GetAtt:
          - GetReportsFunctionC7A3A071
          - Arn
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Join:
          - ""
          - - "arn:"
            - Ref: AWS::Partition
            - ":execute-api:eu-north-1:490004655195:"
            - Ref: BecsApiGateway1D5DB2B6
            - /
            - Ref: BecsApiGatewayDeploymentStageprod3FC6D306
            - /GET/reports
    Metadata:
      aws:cdk:path: BecsCdkStack/BecsApiGateway/Default/reports/GET/ApiPermission.BecsCdkStackBecsApiGateway9CE4D45C.GET..reports
  BecsApiGatewayreportsGETApiPermissionTestBecsCdkStackBecsApiGateway9CE4D45CGETreports60C0C69A:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Fn::GetAtt:
          - GetReportsFunctionC7A3A071
          - Arn
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Join:
          - ""
          - - "arn:"
            - Ref: AWS::Partition
            - ":execute-api:eu-north-1:490004655195:"
            - Ref: BecsApiGateway1D5DB2B6
            - /test-invoke-stage/GET/reports
    Metadata:
      aws:cdk:path: BecsCdkStack/BecsApiGateway/Default/reports/GET/ApiPermission.Test.BecsCdkStackBecsApiGateway9CE4D45C.GET..reports
  BecsApiGatewayreportsGET493B545F:
    Type: AWS::ApiGateway::Method
    Properties:
      AuthorizationType: NONE
      HttpMethod: GET
      Integration:
        IntegrationHttpMethod: POST
        Type: AWS_PROXY
        Uri:
          Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :apigateway:eu-north-1:lambda:path/2015-03-31/functions/
              - Fn::GetAtt:
                  - GetReportsFunctionC7A3A071
                  - Arn
              - /invocations
      ResourceId:
        Ref: BecsApiGatewayreportsF831456D
      RestApiId:
        Ref: BecsApiGateway1D5DB2B6
    Metadata:
      aws:cdk:path: BecsCdkStack/BecsApiGateway/Default/reports/GET/Resource
  BecsApiGatewayreportsPOSTApiPermissionBecsCdkStackBecsApiGateway9CE4D45CPOSTreportsCBDE52A3:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Fn::GetAtt:
          - CreateProductFunctionD4A3469E
          - Arn
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Join:
          - ""
          - - "arn:"
            - Ref: AWS::Partition
            - ":execute-api:eu-north-1:490004655195:"
            - Ref: BecsApiGateway1D5DB2B6
            - /
            - Ref: BecsApiGatewayDeploymentStageprod3FC6D306
            - /POST/reports
    Metadata:
      aws:cdk:path: BecsCdkStack/BecsApiGateway/Default/reports/POST/ApiPermission.BecsCdkStackBecsApiGateway9CE4D45C.POST..reports
  BecsApiGatewayreportsPOSTApiPermissionTestBecsCdkStackBecsApiGateway9CE4D45CPOSTreportsCDC0F43A:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Fn::GetAtt:
          - CreateProductFunctionD4A3469E
          - Arn
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Join:
          - ""
          - - "arn:"
            - Ref: AWS::Partition
            - ":execute-api:eu-north-1:490004655195:"
            - Ref: BecsApiGateway1D5DB2B6
            - /test-invoke-stage/POST/reports
    Metadata:
      aws:cdk:path: BecsCdkStack/BecsApiGateway/Default/reports/POST/ApiPermission.Test.BecsCdkStackBecsApiGateway9CE4D45C.POST..reports
  BecsApiGatewayreportsPOST96506AE4:
    Type: AWS::ApiGateway::Method
    Properties:
      AuthorizationType: NONE
      HttpMethod: POST
      Integration:
        IntegrationHttpMethod: POST
        Type: AWS_PROXY
        Uri:
          Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :apigateway:eu-north-1:lambda:path/2015-03-31/functions/
              - Fn::GetAtt:
                  - CreateProductFunctionD4A3469E
                  - Arn
              - /invocations
      ResourceId:
        Ref: BecsApiGatewayreportsF831456D
      RestApiId:
        Ref: BecsApiGateway1D5DB2B6
    Metadata:
      aws:cdk:path: BecsCdkStack/BecsApiGateway/Default/reports/POST/Resource
  GetReportsFunctionServiceRole35432670:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
        Version: "2012-10-17"
      ManagedPolicyArns:
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
    Metadata:
      aws:cdk:path: BecsCdkStack/GetReportsFunction/ServiceRole/Resource
  GetReportsFunctionServiceRoleDefaultPolicyD29C3A9C:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Action:
              - xray:PutTraceSegments
              - xray:PutTelemetryRecords
            Effect: Allow
            Resource: "*"
          - Action:
              - dynamodb:BatchGetItem
              - dynamodb:GetRecords
              - dynamodb:GetShardIterator
              - dynamodb:Query
              - dynamodb:GetItem
              - dynamodb:Scan
              - dynamodb:ConditionCheckItem
              - dynamodb:BatchWriteItem
              - dynamodb:PutItem
              - dynamodb:UpdateItem
              - dynamodb:DeleteItem
              - dynamodb:DescribeTable
            Effect: Allow
            Resource:
              - Fn::GetAtt:
                  - ProductsTable241ADBFF
                  - Arn
              - Ref: AWS::NoValue
        Version: "2012-10-17"
      PolicyName: GetReportsFunctionServiceRoleDefaultPolicyD29C3A9C
      Roles:
        - Ref: GetReportsFunctionServiceRole35432670
    Metadata:
      aws:cdk:path: BecsCdkStack/GetReportsFunction/ServiceRole/DefaultPolicy/Resource
  GetReportsFunctionC7A3A071:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: cdk-hnb659fds-assets-490004655195-eu-north-1
        S3Key: 8def08512cf29d8b766d0f11dda9731bc5aeb7febd786fcfd0c8fcd81388af2f.zip
      Environment:
        Variables:
          AWS_ACCOUNT_ID: "490004655195"
          AWS_NODEJS_CONNECTION_REUSE_ENABLED: "1"
      Handler: index.getReportListHandler
      MemorySize: 1028
      Role:
        Fn::GetAtt:
          - GetReportsFunctionServiceRole35432670
          - Arn
      Runtime: nodejs20.x
      TracingConfig:
        Mode: Active
    DependsOn:
      - GetReportsFunctionServiceRoleDefaultPolicyD29C3A9C
      - GetReportsFunctionServiceRole35432670
    Metadata:
      aws:cdk:path: BecsCdkStack/GetReportsFunction/Resource
      aws:asset:path: asset.8def08512cf29d8b766d0f11dda9731bc5aeb7febd786fcfd0c8fcd81388af2f
      aws:asset:is-bundled: true
      aws:asset:property: Code
  CreateProductFunctionServiceRole54C12217:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
        Version: "2012-10-17"
      ManagedPolicyArns:
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
    Metadata:
      aws:cdk:path: BecsCdkStack/CreateProductFunction/ServiceRole/Resource
  CreateProductFunctionServiceRoleDefaultPolicy71144764:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Action:
              - xray:PutTraceSegments
              - xray:PutTelemetryRecords
            Effect: Allow
            Resource: "*"
          - Action:
              - dynamodb:BatchGetItem
              - dynamodb:GetRecords
              - dynamodb:GetShardIterator
              - dynamodb:Query
              - dynamodb:GetItem
              - dynamodb:Scan
              - dynamodb:ConditionCheckItem
              - dynamodb:BatchWriteItem
              - dynamodb:PutItem
              - dynamodb:UpdateItem
              - dynamodb:DeleteItem
              - dynamodb:DescribeTable
            Effect: Allow
            Resource:
              - Fn::GetAtt:
                  - ProductsTable241ADBFF
                  - Arn
              - Ref: AWS::NoValue
        Version: "2012-10-17"
      PolicyName: CreateProductFunctionServiceRoleDefaultPolicy71144764
      Roles:
        - Ref: CreateProductFunctionServiceRole54C12217
    Metadata:
      aws:cdk:path: BecsCdkStack/CreateProductFunction/ServiceRole/DefaultPolicy/Resource
  CreateProductFunctionD4A3469E:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: cdk-hnb659fds-assets-490004655195-eu-north-1
        S3Key: 8def08512cf29d8b766d0f11dda9731bc5aeb7febd786fcfd0c8fcd81388af2f.zip
      Environment:
        Variables:
          AWS_ACCOUNT_ID: "490004655195"
          AWS_NODEJS_CONNECTION_REUSE_ENABLED: "1"
      Handler: index.createReportHandler
      MemorySize: 1028
      Role:
        Fn::GetAtt:
          - CreateProductFunctionServiceRole54C12217
          - Arn
      Runtime: nodejs20.x
      TracingConfig:
        Mode: Active
    DependsOn:
      - CreateProductFunctionServiceRoleDefaultPolicy71144764
      - CreateProductFunctionServiceRole54C12217
    Metadata:
      aws:cdk:path: BecsCdkStack/CreateProductFunction/Resource
      aws:asset:path: asset.8def08512cf29d8b766d0f11dda9731bc5aeb7febd786fcfd0c8fcd81388af2f
      aws:asset:is-bundled: true
      aws:asset:property: Code
  CDKMetadata:
    Type: AWS::CDK::Metadata
    Properties:
      Analytics: v2:deflate64:H4sIAAAAAAAA/1VPTW+DMAz9Lb0Hj7bSeqabdtuH6O7IBK8NkARhZwgh/vsUWDV2eh9+sp8PsD89QrrDgRNdNUlrSpgugrpROHAxVaND66sSpk8sW1JPX24hs8LOXFFowBGmnFiyzsTphmZa++BEPVPX+tGSk+hu1EXwuqxcSU7sQ6/pjPwnfneu/JXk5qtorWxWBi1MuV+bLfjhW6PHKFc2qxZtWSFM0aLeGmbjXQy8BKfFeHePFM5XVDO8LXCfKj4WyEzCkEVQfIRz0A1JLDr/a/oepAuillx8yrjr9oFZxQtQ88P3IYX9CdJdzcYkfXBiLEG+4g/1+nAolQEAAA==
    Metadata:
      aws:cdk:path: BecsCdkStack/CDKMetadata/Default
Outputs:
  BecsApiGatewayEndpoint6998FDD0:
    Value:
      Fn::Join:
        - ""
        - - https://
          - Ref: BecsApiGateway1D5DB2B6
          - .execute-api.eu-north-1.
          - Ref: AWS::URLSuffix
          - /
          - Ref: BecsApiGatewayDeploymentStageprod3FC6D306
          - /
Parameters:
  BootstrapVersion:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /cdk-bootstrap/hnb659fds/version
    Description: Version of the CDK Bootstrap resources in this environment, automatically retrieved from SSM Parameter Store. [cdk:skip]

